// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_cFKoVORpDXvGLDjYrOeTnGVizMDnlNE',
    appId: '1:982884383347:web:2cd1ee7725771443a84806',
    messagingSenderId: '982884383347',
    projectId: 'mynotes-f13a3',
    authDomain: 'mynotes-f13a3.firebaseapp.com',
    storageBucket: 'mynotes-f13a3.appspot.com',
    measurementId: 'G-S3TDL9VD21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXgyzpE_7y5ldjipJrdmT_TFVYiopl1N0',
    appId: '1:982884383347:android:d11056a18fbe5fa1a84806',
    messagingSenderId: '982884383347',
    projectId: 'mynotes-f13a3',
    storageBucket: 'mynotes-f13a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd2ZyJoFpOLhRN-WojmRcX-kMEMKnPwS4',
    appId: '1:982884383347:ios:105242dc9d036a3aa84806',
    messagingSenderId: '982884383347',
    projectId: 'mynotes-f13a3',
    storageBucket: 'mynotes-f13a3.appspot.com',
    iosClientId: '982884383347-saoto1o9k7kgkcpgor20pgt6ja3f56sh.apps.googleusercontent.com',
    iosBundleId: 'com.davidoh.mynotes',
  );
}
